# Generated by Django 5.0.2 on 2025-02-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
    ]
