# Generated by Django 5.0.2 on 2025-02-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_student_alter_project_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('COMP', 'Computer Engineering'), ('IT', 'Information Technology'), ('ENTC', 'Electronics & Telecommunication'), ('MECH', 'Mechanical Engineering'), ('ARE', 'Authomation & Robotics Engineering')], max_length=100),
        ),
    ]
