# Generated by Django 5.0.2 on 2025-04-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_faculty_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['student__batch']},
        ),
        migrations.AddField(
            model_name='faculty',
            name='batch',
            field=models.CharField(choices=[('A', 'Batch A'), ('B', 'Batch B'), ('C', 'Batch C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('SE-IT-B', 'SE-IT-B'), ('SE-IT-A', 'SE-IT-A')], max_length=100),
        ),
    ]
