# Generated by Django 5.0.2 on 2025-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_project_options_faculty_batch_student_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group_members',
            field=models.TextField(default='', help_text="Enter group members' names separated by commas"),
            preserve_default=False,
        ),
    ]
